#pragma once

enum class LCUBEDIRECION
{
	LDIREC_TOP = 0,
	LDIREC_NORTH = 1,
	LDIREC_WEST = 2,
	LDIREC_SOUTH = 3,
	LDIREC_EAST = 4,
	LDIREC_BOTTOM = 5,
	LDIREC_END
};

enum class LANDCOMMAND
{
	LCOMMAND_HIGHLIGHT_SURFACE_SINGLE = 0,
	LCOMMAND_HIGHLIGHT_SURFACE_LINKED,
	LCOMMAND_HIGHLIGHT_NEWCUBE,
	LCOMMAND_ERASE_CUBE,
	LCOMMAND_MAKE_CUBE,
	LCOMMAND_CHANGE_SURFACE,
	LCOMMAND_END
};