#pragma once

enum class SOUND_NAME
{
	SOUND_WALK,
	SOUND_SHOT_MACHINEGUN,
	SOUND_SHOT_SHOTGUN,
	SOUND_JUMP,
	SOUND_THROW_GRANADE,
	SOUND_EXPLOSION_SMALL,
	SOUND_EXPLOSION_HUGE,
	SOUND_FIRE,
	SOUND_PAGE_OPEN,
	SOUND_WEAPONSLOT,
	SOUND_HACK,
	SOUND_WARNING,
	SOUND_BGM_NORMAL,
	SOUND_BGM_BATTLE,
	SOUND_BEEP,
	SOUND_MELEE,
	SOUND_END
};

enum class SOUND_CHANNEL
{
	CH_PLAYER_WEAPON,
	CH_PLAYER_ACT,
	CH_MONSTER_GUN,
	CH_MONSTER_SHOTGUN,
	CH_MONSTER_MELEE,
	CH_MONSTER_ACT,
	CH_INGAME_EXPLOSION,
	CH_INGAME_FIRE,
	CH_SYSTEM_UI,
	CH_SYSTEM_BGM,
	CH_END
};
