#pragma once

enum class ITEMINDEX
{
	ITEM_SHOTGUN,
	ITEM_SHOTGUN_KIT,
	ITEM_AMMO,
	ITEM_CHRISTMAS_HAT,
	ITEM_COAL_INGOT,
	ITEM_COAL_ORE_CHUNK,
	ITEM_COPPER_INGOT,
	ITEM_COPPER_ORE_CHUNK,
	ITEM_IRON_INGOT,
	ITEM_IRON_ORE_CHUNK,
	ITEM_GOLD_INGOT,
	ITEM_GOLD_ORE_CHUNK,
	ITEM_MACHINGUN_CRAFTINGKIT,
	ITEM_MAFIAHAT,
	ITEM_FISH,
	ITEM_MEAT,
	ITEM_CHAINSAW,
	ITEM_JAM,
	ITEM_ARROW,
	ITEM_DOUBLESHOTGUN,
	ITEM_END
};

enum class ITEMTYPE
{
	ITEM_TYPE_WEAPON,
	ITEM_TYPE_HAT,
	ITEM_TYPE_TOOL,
	ITEM_TYPE_FOOD,
	ITEM_TYPE_MINERAL,
	ITEM_TYPE_POTION,
	ITEM_TYPE_AMMO,
	ITEM_TYPE_ETC,
	ITEM_TYPE_END
};

enum class ITEMTAG
{
	ITEM_TAG_PUSH,
	ITEM_TAG_BURN,
	ITEM_TAG_QUIET,
	ITEM_TAG_HEAVYDEMAGE,
	ITEM_TAG_DISH,
	ITEM_TAG_HIGHPRICE,
	ITEM_TAG_REFINED,
	ITEM_TAG_CANROTTEN,
	ITEM_TAG_END
};
