#pragma once



enum class INTERACTION
{
	INTER_BULLET_STRAIGHT,
	INTER_BULLET_MACHINEGUN,
	INTER_BULLET_PARABOLA,
	INTER_THORW_OBJECT,
	INTER_THORW_MINE,
	INTER_THORW_GRANADE,
	INTER_THORW_DINAMITE,
	INTER_MELEE_NORMAL,
	INTER_MELEE_SHOTGUN,
	INTER_MELEE_CHAINSAW,
	INTER_EXPLOSION_NORMAL,
	INTER_FIRE,
	INTER_END
};